//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGM.Payments.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AvantGrandeMSEntities : DbContext
    {
        public AvantGrandeMSEntities()
            : base("name=AvantGrandeMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuthorizeAccount> AuthorizeAccounts { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeePropertyPermission> EmployeePropertyPermissions { get; set; }
        public virtual DbSet<PaymentToProperty> PaymentToProperties { get; set; }
    }
}
