//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGM.Payments.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentToProperty
    {
        public int PaymentID { get; set; }
        public int AuthAccountID { get; set; }
        public string PropertyID { get; set; }
    
        public virtual AuthorizeAccount AuthorizeAccount { get; set; }
    }
}
